**If you lost points on the last checkpoint you can get them back by responding to TA/IA feedback**  

Update/change the relevant sections where you lost those points, make sure you respond on GitHub Issues to your TA/IA to call their attention to the changes you made here.

Please update your Timeline... no battle plan survives contact with the enemy, so make sure we understand how your plans have changed.

# COGS 108 - Data Checkpoint

# Names

- Helen Yang
- Janette Lim
- Yiyi Huang
- Vanessa Hinds
- Ryan Paquia

# Research Question

***Updated Research Question According to TA Feedback:*** <br>
How do fluctuations in airfare rates, encompassing changes in pricing, discounts, seasonal offers, and other variations across airlines (Delta, Jetblue Airways, Spirit, American Airlines, and United), impact the volume of travel during the summer season (June to August) compared to the spring season (April to May), specifically in terms of remaining airplane seats for planes that fly within the United States?

## Background and Prior Work

The global tourism industry is largely influenced by a myriad of factors, including economic conditions, cultural appeal, and accessibility of transportation. One of the crucial factors that shape travel patterns is the fluctuation and diversity in airfare rates offered by airlines. The interplay between airfare pricing dynamics, seasonal discounts, and variations across multiple airlines can significantly impact the decisions of tourists from various regions. 

This research delves into the intricate relationship between airfare rates and the number of tourists in the US. Furthermore, airfare rates are known to fluctuate due to various reasons including operational costs, fuel prices, market competition, and the varying strategies adopted by airlines Delta, Jetblue Airways, Spirit, American Airlines, and United to promote more ticket purchases from the customers. These pricing variations are often influenced by seasonal discounts, special offers, and promotional packages that affect the affordability and desirability of travel for potential tourists. Through an in-depth analysis of these dynamics, this research aims to shed light on the interconnection between airline pricing strategies and the influx of tourists, thereby offering valuable insights for stakeholders within the tourism industry to optimize their strategies and cater to the demands of travelers during peak seasons.  

Furthermore, from the initial research on the relationship between ticket price rates and tourism dynamics, it became evident that the fundamental correlation between ticket prices, airline costs, and their impact on a country’s Gross Domestic Product (GDP). It mostly suggests that improved airport infrastructure and direct airline connections are key factors in reducing costs, which encourages tourism in specific destinations. The interdependence between air transport and tourism is essential due to their derived nature, where most air travel is motivated by the need to reach specific destinations for various purposes, notably tourism-related activities such as leisure, business, and visiting friends and relatives, among others. According to studies by Papatheodorou, enhanced accessibility through improved airport infrastructure and direct airline connections can reduce costs (both monetary and time-related) and stimulate tourism in specific destinations <a name="cite_ref-1"></a>[<sup>1<sup>](#cite_note-1). Furthermore, the study by Hong Tsui underscores the significance of the Low-Cost Carrier (LCC) impact on New Zealand's major regions and tourist destinations. Understanding the LCC's influence on key areas which collectively drive a substantial share of the country's domestic guest nights, is vital. The study highlights the potential benefits of expanding LCC operations to smaller regions, potentially stimulating domestic tourism demand and fostering economic growth, emphasizing the crucial relationship between affordable air travel and the broader economic landscape <a name="cite_ref-2"></a>[<sup>2<sup>](#cite_note-2).

**Reference:**

1. <a name="cite_note-1"></a> [^](#cite_ref-1) Papatheodorou, Andreas. “A review of research into air transport and tourism: Launching the Annals of Tourism Research Curated Collection on Air Transport and Tourism” Annals of Tourism Research vol. 87 (2021): 103151. ISSN 0160-7383, doi.org:10.1016/j.annals.2021.103151 https://urldefense.com/v3/__https://www.sciencedirect.com/science/article/pii/S016073832100013X*5Cn__;JQ!!Mih3wA!HyxOyjUQkrs9KtWJJnQjmb5vlLo3RIF-cRVeJ3yZBpfNkI-0VptGPxX1ld_VKW8yUAFREJ6hsNLMtQy5j7M$ 

2. <a name="cite_note-2"></a> [^](#cite_ref-2) Hong Tsui, Kan Wai. “Does a low-cost carrier lead the domestic tourism demand and growth of New Zealand?.” Tourism management vol. 60 (2017): 390-403. doi:10.1016/j.tourman.2016.10.013 https://urldefense.com/v3/__https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7115627/*5Cn__;JQ!!Mih3wA!HyxOyjUQkrs9KtWJJnQjmb5vlLo3RIF-cRVeJ3yZBpfNkI-0VptGPxX1ld_VKW8yUAFREJ6hsNLMdXq1i1A$

# Hypothesis

- Our team hypothesizes that a substantial decrease in airfare rates offered by airlines will correspond with a notable increase in the volume of tourists. 

- Our reasoning behind this hypothesis is grounded in the basic economic principle that lower prices often stimulate demand. We expect reduced airfare rates, including discounts and promotional offers, will make travel more financially feasible and attractive for tourists.

# Data

The ideal dataset we would want to answer our question would contain variables dictating start and destination cities, dates across many months/years broken down to month intervals, the price for airplane tickets for those dates, as well as the number of seats taken and remaining on those flights. Given that airplane travel is used by an incredible number of people we would need observations at least numbering in the thousands, as well as data that includes a large range of dates spanning the course of at least a year. Data that is broken down month by month or week by week would be ideal because this means we can analyze many intervals over the course of the dates given by the data. In addition to this, we would want to eliminate as many confounding variables as we can such as COVID and inflation. So we want datasets that don’t coincide with COVID dates and data that adjust for inflation. This data would be collected by people who work in the airline industry, that track all the data needed to run an airline. They would obtain the data through the airport’s database and store them in a CSV file containing all the variables our team would need to run our project. For our data collection process, we would ideally get the data from a government or airline website, or a dataset from Kaggle formed through web scraping.

## Data overview

For each dataset include the following information
- Dataset #1
  - Dataset Name: Passengers: All Carriers - All Airports
  - Link to the dataset: https://urldefense.com/v3/__https://www.kaggle.com/datasets/pablodroca/flight-prices-2m*5Cn__;JQ!!Mih3wA!HyxOyjUQkrs9KtWJJnQjmb5vlLo3RIF-cRVeJ3yZBpfNkI-0VptGPxX1ld_VKW8yUAFREJ6hsNLMI8r3Kuo$ 
  - Number of observations: 2 million
  - Number of variables: 27
- Dataset #2
  - Dataset Name: Aircraft Seats
  - Link to the dataset: https://urldefense.com/v3/__https://docs.google.com/spreadsheets/d/1ev6P7GnBWgXSI_V-z0M5Iqn2F8jynIni_yGIPGwRrHM/edit?usp=sharing*5Cn__;JQ!!Mih3wA!HyxOyjUQkrs9KtWJJnQjmb5vlLo3RIF-cRVeJ3yZBpfNkI-0VptGPxX1ld_VKW8yUAFREJ6hsNLM3OZhHQM$ 
  - Number of observations: 39
  - Number of variables: 3

For the first dataset, it provides 2M rows of the domestic flight prices. Some important variables in the dataset are prices, flight information, time and date, and destination which contain numeric, categorical, and temporal data types. Prices would be important since it can measure the affordability, market demand, and economic conditions that affect the ticket prices, and the flight information is important considering the total number of seats and airline market share. Time and date is also important because of the seasonal trends analysis as well as the temporal demand patterns. Lastly, the destination is significant because it allows for deeper analysis of the regional travel patterns and geographic demand variations. We plan to clean the dataset by keeping only important information such as flight date, destination airport, total fare, and others and dropping the rows that are irrelevant. Also, we plan to drop any unclear description or redundant information to clean the dataset. 

The second dataset provides the total number of seats for each aircraft. By having the total number of seats and how many of them are occupied, it is going to be helpful for analyzing the occupancy during the peak and non-peak seasons. The matrics of this dataset are the aircraft names and total seats which are categorical and numeric data types. For the second dataset, we plan to clean it by removing it's "Source" column as it contains links to the source of data for the "Data" column and so will not be useful in relation to the rest of the data in both datasets.

We plan to combine two datasets by inserting the aircraft names from the second dataset to the equipment description of the first dataset. Combining the first and second dataset, we plan to compare the prices, traveling seasons, and variations across airlines for analyzing the impact they have on the volume of travel, which will eventually derive us to the resulting foot traffic in cities across the United States.

## Flight Prices

In [39]:
import numpy as np
import pandas as pd

In [40]:
df = pd.read_csv("itineraries_random_2M-Copy1.csv")
df.head()

,legId,searchDate,flightDate,startingAirport,destinationAirport,fareBasisCode,travelDuration,elapsedDays,isBasicEconomy,isRefundable,...,segmentsArrivalTimeEpochSeconds,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsAirlineCode,segmentsEquipmentDescription,segmentsDurationInSeconds,segmentsDistance,segmentsCabinCode
0,620cd51404373b9bdbbc46a0b657573c,5/29/2022,6/18/2022,LAX,ATL,Y0N,PT4H19M,0,False,False,...,1655606940,2022-06-18T22:49:00.000-04:00,ATL,LAX,Delta,DL,Airbus A321,15540,1943,coach
1,8622d132e890b398c0ad1d62b0232f54,5/3/2022,6/24/2022,CLT,LAX,MA0OA0MQ,PT8H10M,0,False,False,...,1656078240||1656103200,2022-06-24T09:44:00.000-04:00||2022-06-24T13:4...,ATL||LAX,CLT||ATL,Delta||Delta,DL||DL,Boeing 717||Airbus A321,4440||16680,228||1943,coach||coach
2,6f419788769ddb3802d047272ad0a54d,5/2/2022,6/30/2022,LGA,ATL,LAVQA0ML,PT11H54M,1,False,False,...,1656645360||1656676380,2022-06-30T23:16:00.000-04:00||2022-07-01T07:5...,MIA||ATL,LGA||MIA,Delta||Delta,DL||DL,Boeing 737-800||Boeing 737-900,11820||6780,1104||596,coach||coach
3,41f3cd0a63603895e13b5b77630bd84e,6/10/2022,8/4/2022,LAX,SFO,MH7OASMN,PT1H20M,0,False,False,...,1659669600,2022-08-04T20:20:00.000-07:00,SFO,LAX,Alaska Airlines,AS,Embraer 175,4800,339,coach
4,7f5d8684b672dd3593e30ee946264c31,6/24/2022,7/20/2022,LGA,DFW,LAVQA0BQ,PT6H41M,0,True,False,...,1658337240||1658351760,2022-07-20T13:14:00.000-04:00||2022-07-20T16:1...,ATL||DFW,LGA||ATL,Delta||Delta,DL||DL,Airbus A320||Airbus A321,9540||8460,762||725,coach||coach

In [41]:
# List of columns to keep
selected_columns = [
    'legId',
    'flightDate',
    'startingAirport',
    'destinationAirport',
    'isBasicEconomy',
    'isNonStop',
    'baseFare',
    'totalFare',
    'seatsRemaining',
    'segmentsAirlineName',
    'segmentsEquipmentDescription',
    'segmentsDurationInSeconds'
]

In [42]:
# Creating a new DataFrame with only the selected columns
cleaned_column_df = df[selected_columns]

In [43]:
# Dropping rows with missing values
cleaned_column_df = cleaned_column_df.dropna()

In [44]:
# Renaming the columns
column_mapping = {
    'legId': 'Leg ID',
    'flightDate': 'Flight Date',
    'startingAirport': 'Starting Airport',
    'destinationAirport': 'Destination Airport',
    'isBasicEconomy': 'Basic Economy',
    'isNonStop': 'Non-Stop',
    'baseFare': 'Base Fare',
    'totalFare': 'Total Fare',
    'seatsRemaining': 'Seats Remaining',
    'segmentsAirlineName': 'Airline Name',
    'segmentsEquipmentDescription': 'Equipment Description',
    'segmentsDurationInSeconds': 'Duration in seconds'
}

cleaned_column_names_df = cleaned_column_df.rename(columns=column_mapping)

In [45]:
# Modifying data stored in the "Airline Name" column
cleaned_column_names_df['Airline Name'] = cleaned_column_names_df['Airline Name'].apply(lambda s : s.split('||')[0])

In [46]:
# Modifying data stored in the "Equipment Description" column
cleaned_column_names_df['Equipment Description'] = cleaned_column_names_df['Equipment Description'].apply(lambda s : str(s).split('||')[-1])
cleaned_column_names_df['Equipment Description'] = cleaned_column_names_df['Equipment Description'].str.lower().str.capitalize()

In [ ]:
# Modifying data stored in the "Duration in seconds" column
cleaned_column_names_df['Duration in seconds'] = cleaned_column_names_df['Duration in seconds'].apply(lambda s: sum(int(value) for value in str(s).split('||') if value.isdigit()))

In [48]:
# Renaming the dataframe
df_prices = cleaned_column_names_df

In [49]:
df_prices.describe()

          Base Fare    Total Fare  Seats Remaining  Duration in seconds
count  1.027778e+06  1.027778e+06     1.027778e+06         1.027778e+06
mean   3.349188e+02  3.862543e+02     5.628973e+00         1.675197e+04
std    1.973420e+02  2.106954e+02     2.964580e+00         6.731129e+03
min    2.000000e+00  2.397000e+01     0.000000e+00         2.760000e+03
25%    1.897700e+02  2.305800e+02     3.000000e+00         1.152000e+04
50%    3.073600e+02  3.571000e+02     7.000000e+00         1.620000e+04
75%    4.483800e+02  5.066000e+02     8.000000e+00         2.196000e+04
max    4.407440e+03  4.752600e+03     1.000000e+01         4.578000e+04

In [50]:
df_prices.dtypes

Leg ID                    object
Flight Date               object
Starting Airport          object
Destination Airport       object
Basic Economy               bool
Non-Stop                    bool
Base Fare                float64
Total Fare               float64
Seats Remaining            int64
Airline Name              object
Equipment Description     object
Duration in seconds        int64
dtype: object

In [51]:
df_prices.head()

,Leg ID,Flight Date,Starting Airport,Destination Airport,Basic Economy,Non-Stop,Base Fare,Total Fare,Seats Remaining,Airline Name,Equipment Description,Duration in seconds
0,620cd51404373b9bdbbc46a0b657573c,6/18/2022,LAX,ATL,False,True,943.26,1028.61,7,Delta,Airbus a321,15540
1,8622d132e890b398c0ad1d62b0232f54,6/24/2022,CLT,LAX,False,False,479.07,537.10,9,Delta,Airbus a321,21120
2,6f419788769ddb3802d047272ad0a54d,6/30/2022,LGA,ATL,False,False,328.38,382.21,9,Delta,Boeing 737-900,18600
3,41f3cd0a63603895e13b5b77630bd84e,8/4/2022,LAX,SFO,False,True,189.77,218.60,7,Alaska Airlines,Embraer 175,4800
4,7f5d8684b672dd3593e30ee946264c31,7/20/2022,LGA,DFW,True,False,171.16,207.60,9,Delta,Airbus a321,18000

In [52]:
# Cheking for different aircrafts in the dataset
df_prices.groupby('Equipment Description').count()

,Leg ID,Flight Date,Starting Airport,Destination Airport,Basic Economy,Non-Stop,Base Fare,Total Fare,Seats Remaining,Airline Name,Duration in seconds
Equipment Description,,,,,,,,,,,
,49405,49405,49405,49405,49405,49405,49405,49405,49405,49405,49405
Airbus a220-100,17272,17272,17272,17272,17272,17272,17272,17272,17272,17272,17272
Airbus a319,82196,82196,82196,82196,82196,82196,82196,82196,82196,82196,82196
Airbus a319-321,12612,12612,12612,12612,12612,12612,12612,12612,12612,12612,12612
Airbus a320,95837,95837,95837,95837,95837,95837,95837,95837,95837,95837,95837
Airbus a321,140479,140479,140479,140479,140479,140479,140479,140479,140479,140479,140479
Airbus a330-200,276,276,276,276,276,276,276,276,276,276,276
Airbus a330-300,128,128,128,128,128,128,128,128,128,128,128
Airbus industrie a320 sharklets,16453,16453,16453,16453,16453,16453,16453,16453,16453,16453,16453
Airbus industrie a321 sharklets,33803,33803,33803,33803,33803,33803,33803,33803,33803,33803,33803
Airbus industrie a350-900,265,265,265,265,265,265,265,265,265,265,265
Boeing 717,34046,34046,34046,34046,34046,34046,34046,34046,34046,34046,34046
Boeing 737,1165,1165,1165,1165,1165,1165,1165,1165,1165,1165,1165
Boeing 737 max 8,15119,15119,15119,15119,15119,15119,15119,15119,15119,15119,15119
Boeing 737 max 9,13287,13287,13287,13287,13287,13287,13287,13287,13287,13287,13287
Boeing 737-700,11731,11731,11731,11731,11731,11731,11731,11731,11731,11731,11731
Boeing 737-800,162522,162522,162522,162522,162522,162522,162522,162522,162522,162522,162522
Boeing 737-900,88071,88071,88071,88071,88071,88071,88071,88071,88071,88071,88071
Boeing 757,9758,9758,9758,9758,9758,9758,9758,9758,9758,9758,9758
Boeing 757-200,10834,10834,10834,10834,10834,10834,10834,10834,10834,10834,10834
Boeing 757-300,8828,8828,8828,8828,8828,8828,8828,8828,8828,8828,8828
Boeing 767,671,671,671,671,671,671,671,671,671,671,671
Boeing 767-300,180,180,180,180,180,180,180,180,180,180,180
Boeing 777,6531,6531,6531,6531,6531,6531,6531,6531,6531,6531,6531
Boeing 777-200,1271,1271,1271,1271,1271,1271,1271,1271,1271,1271,1271
Boeing 777-300er,2699,2699,2699,2699,2699,2699,2699,2699,2699,2699,2699
Boeing 787,1,1,1,1,1,1,1,1,1,1,1
Boeing 787-8,1325,1325,1325,1325,1325,1325,1325,1325,1325,1325,1325
Boeing 787-9,1231,1231,1231,1231,1231,1231,1231,1231,1231,1231,1231
Canadair regional jet,1954,1954,1954,1954,1954,1954,1954,1954,1954,1954,1954
Canadair regional jet 900,36394,36394,36394,36394,36394,36394,36394,36394,36394,36394,36394
Canadian regional jet 700,5435,5435,5435,5435,5435,5435,5435,5435,5435,5435,5435
Cessna,693,693,693,693,693,693,693,693,693,693,693
Embraer 170,13952,13952,13952,13952,13952,13952,13952,13952,13952,13952,13952
Embraer 175,58021,58021,58021,58021,58021,58021,58021,58021,58021,58021,58021
Embraer 175 (enhanced winglets),59845,59845,59845,59845,59845,59845,59845,59845,59845,59845,59845
Embraer 190,28089,28089,28089,28089,28089,28089,28089,28089,28089,28089,28089
Embraer emb-145,2588,2588,2588,2588,2588,2588,2588,2588,2588,2588,2588
Embraer rj145,2128,2128,2128,2128,2128,2128,2128,2128,2128,2128,2128
Fairchild dornier 328,109,109,109,109,109,109,109,109,109,109,109
Pilatus pc-12,288,288,288,288,288,288,288,288,288,288,288
Tecnam p2012 traveler,286,286,286,286,286,286,286,286,286,286,286

In [53]:
# Renaming redundant aircraft names and dropping "Boeing 787" due to unclear description
df_prices['Equipment Description'] = df_prices['Equipment Description'].replace({
    'Airbus industrie a320 sharklets': 'Airbus a320',
    'Airbus industrie a321 sharklets': 'Airbus a321',
    'Embraer 175 (enhanced winglets)': 'Embraer 175'
})
df_prices = df_prices[df_prices['Equipment Description'] != 'Boeing 787']

In [57]:
# Dropping empty inputs/ NA
df_prices['Equipment Description'] = df_prices['Equipment Description'].replace('', pd.NA)
df_prices = df_prices.dropna(subset=['Equipment Description'])
df_prices.head()

,Leg ID,Flight Date,Starting Airport,Destination Airport,Basic Economy,Non-Stop,Base Fare,Total Fare,Seats Remaining,Airline Name,Equipment Description,Duration in seconds
0,620cd51404373b9bdbbc46a0b657573c,6/18/2022,LAX,ATL,False,True,943.26,1028.61,7,Delta,Airbus a321,15540
1,8622d132e890b398c0ad1d62b0232f54,6/24/2022,CLT,LAX,False,False,479.07,537.10,9,Delta,Airbus a321,21120
2,6f419788769ddb3802d047272ad0a54d,6/30/2022,LGA,ATL,False,False,328.38,382.21,9,Delta,Boeing 737-900,18600
3,41f3cd0a63603895e13b5b77630bd84e,8/4/2022,LAX,SFO,False,True,189.77,218.60,7,Alaska Airlines,Embraer 175,4800
4,7f5d8684b672dd3593e30ee946264c31,7/20/2022,LGA,DFW,True,False,171.16,207.60,9,Delta,Airbus a321,18000

## Aircraft Seats

In [55]:
# Load in Dataset Seats
df_seats = pd.read_csv("Aircraft_Seats.csv")

In [58]:
# Formatting the Dataset Seats for merge with Dataset Prices
df_seats['Equipment Description'] = df_seats['Equipment Description'].str.lower().str.capitalize()

# Omit "Source" column
df_seats.drop('Source', axis=1)

              Equipment Description  Total Seats
0                  Boeing 777-300er          396
1                      Boeing 787-9          296
2                        Boeing 717          106
3                        Boeing 737          126
4                  Boeing 737 max 8          178
5                  Boeing 737 max 9          193
6                    Boeing 737-700          126
7                    Boeing 737-800          162
8                    Boeing 737-900          177
9                        Boeing 757          178
10                   Boeing 757-200          178
11                   Boeing 757-300          240
12                       Boeing 767          216
13                   Boeing 767-300          269
14                       Boeing 777          305
15                   Boeing 777-200          399
16                     Boeing 787-8          242
17            Canadair regional jet           70
18        Canadair regional jet 900           80
19                      Embraer 175           78
20                      Embraer 170           70
21                      Embraer 190           98
22                  Embraer emb-145           50
23                    Embraer rj145           50
24            Fairchild dornier 328           33
25                    Pilatus pc-12            6
26            Tecnam p2012 traveler           11
27  Airbus industrie a320 sharklets          180
28  Airbus industrie a321 sharklets          200
29        Airbus industrie a350-900          306
30                  Airbus a220-100          135
31                      Airbus a319          110
32                      Airbus a320          180
33                      Airbus a321          200
34                  Airbus a319-321          110
35                  Airbus a330-200          260
36                  Airbus a330-300          290
37        Canadian regional jet 700           68
38                           Cessna           19

# Ethics & Privacy

**Data Collection**

We are using already-existing data, which is open source and free for use. We cannot control how the data was collected, but we do have the skills to determine if the datasets are ethically built. Due to airline policies, the PNR cannot be handed out outside of the operational team, sometimes inclusive of law enforcement. This is reflected in the datasets we will be using, as they do not include passengers’ names, ages, passport numbers, nationality, or other PII. This ensures passengers’ privacy and safety. 

The bias in the data we are using is limited by the fact that we are not considering passengers’ demographics (i.e. race, ethnicity, age, etc.). However, we are indirectly analyzing the influence of socioeconomic status on both airfares and passenger influx. This is partly because some airlines are low-cost carriers while others are not (think JetBlue versus Delta). To this end, we will ensure to consider what type of carriers we are including in our own data. 

**Data Storage**

Since the data we are using is open source, we cannot encrypt the datasets themselves, but we can still make sure to remove any PII from our analysis if we find an extra dataset that we may want to work with to expand the scope of our project. We will have our own data on a public repository on GitHub, which means that a user technically can request their personal data be removed if they recognize an observation being their own. However, this is unlikely as virtually no PII is needed for our project. 

**Analysis**

One limitation is that not all base rates for tickets include the same perks and amenities. For example, low-cost carriers nearly always limit the amount of bags per passenger, sometimes without the ability to pay for an extra bag. However, our analysis does not take into consideration the cost of these perks or whether the passenger elects to purchase additional benefits. We are solely interested in the price of the fare itself versus the amount of passengers flying with individual airlines to and from particular destinations. 

We will be using statistical analyses such as correlation for our project, which aims to find a relationship but not a cause. This would mean that there may be underlying data influencing our conclusions that we are not taking into account. We can acknowledge this in the discussion of our project. However, our visualizations, etc. will attempt to be as honest as possible to the variables denoted in our question. 

**Deployment**

If we find that our content is harmful or can become harmful, we can quickly mitigate this by making the repository inaccessible to the public via GitHub. However, we cannot fully control how other users who fork our repository may use our data. This is why we are being careful with deleting PII and demographic information. We want to prevent said users from abusing passengers’ safety and privacy.

# Team Expectations

- We expect a comprehensive weekly plan during our meetings, outlining each team member's designated tasks. It is expected that every team member takes complete ownership and responsibility for their assigned task.

- We expect every team member to actively participate in the scheduled meetings and hold respectful communication for better collaboration. 

- We expect our team members to communicate respectfully if there is a disagreement regarding certain decisions within the project and to be open to compromise, constructive criticism, and collaboration if necessary.

# Project Timeline Proposal

| Meeting Date | Meeting Time | Completed Before Meeting | Discuss at Meeting |
|--------------|--------------|--------------------------|--------------------|
| 10/23        | 3 PM         | Read & Think about COGS 108 expectations; brainstorm topics/questions | Determine best form of communication; Discuss and decide on final project topic; discuss hypothesis; begin background research |
| 10/29        | 5 PM         | Do background research on topic | Discuss ideal dataset(s) and ethics; draft project proposal |
| 11/1         | 5 PM         | Edit, finalize, and submit proposal; Search for datasets | Assign group members to lead each specific part |
| 11/10        | 6 PM         | Import & Wrangle Data; EDA | Review/Edit wrangling/EDA; Discuss Analysis Plan |
| 11/16        | 12 PM        | Begin Analysis | Discuss/edit Analysis; Complete project check-in 1 |
| 11/26        | 12 PM        | Complete analysis; Draft results/conclusion/discussion | Complete project check-in 2 |
| 12/13        | Before 11:59 PM | NA | Turn in Final Project & Group Project Surveys |